### ISSUE TITLE
Categorization system

### ISSUE THREAD

**Issue by Ruberoni** [Ruberoni/notes-project#23]
## Overview
Make use of user categories to give the possibility of filter the notes.

## Workaround
Make a dropdown list where I can select the categories to filter.\
Specifying:
- each item in the dropdown will be the category + a checkbox
- every category with the checkbox marked will be count in the filter
- marking a checkbox updates the filter

The filter could be a in React state\
**Should the filter be in the context?**\
No, the source of truth (user categories) is the only in the context

### Difficult alternative
- Don't write anything in App.js
- Don't write anything to Notes Context

To do this, I need a way to pass data to the children components of `LateralSection` (where NotesList is)

The filter could be an array of categories id

### Categories Filter
Dropdown list with selectable categories, selecting a category applies de filter.\
Use ChakraUI hook `useCheckboxGroup`

## Task list
- [X] Categories Filter component
- [X] Pass props. to children
- [X] Update notes list
- [x] Fix types 
- [x] Improve design
- [x] Clear all button

## References
https://stackoverflow.com/a/32371612
